rm ~/.zshrc;
rm ~/.vimrc;
rm ~/.inputrc;
rm ~/.tmux.conf;
rm ~/.gitconfig;
ln -s ~/dotfiles/.zshrc ~/.zshrc;
ln -s ~/dotfiles/.vimrc ~/.vimrc;
ln -s ~/dotfiles/.inputrc ~/.inputrc;
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf;
ln -s ~/dotfiles/.gitconfig ~/.gitconfig;
